### ISSUE TITLE
Add web as a platform?

### ISSUE THREAD

**Issue by Aldo111** [MeixDev/DiscordManager#2]
Found this on pub as I was seeking to add Discord sign in to my AngularDart app. I was curious if it would be possible to add web as a platform; A quick browse didn't reveal anything too flutter-specific but I'm only a flutter novice so not sure if you used some specific flutter library here. 

If there's no explicit flutter dep, it would be great if you made this available as a general web+flutter library!

**Comment by MeixDev** [comment]
Hey ! Thanks for your interest !

It's currently in my roadmap to try to update the package with some Web Implementation, but that requires some Javascript implementation and linking it with dart:js ; as the flow on mobile is Flutter-dependant with the uni_links and url_launcher dependencies. Can't say how long it will take as I can't really focus anytime on this project for the past weeks, and I'm not too great when it comes to Javascript.

It will happen, someday. Hopefully sooner than later !

**Comment by Aldo111** [comment]
Ah gotcha no worries! I ended up doing my Discord sign in without any libraries with AngularDart and Dart on the backend so all good.

Feel free to close this issue!

**Comment by MeixDev** [comment]
Glad you could manage !
