### ISSUE TITLE
Support for crypto ^3.0.0

### ISSUE THREAD

**Issue by Sharaddition** [MeixDev/DiscordManager#5]
Since all version of discord_manager depends on crypto ^2.1.4 it is not compatible with google fonts and other libraries.
Please update the package.

**Comment by MeixDev** [comment]
Interesting problem ! I'll try to take time for this, and hopefully to update it to Null Safety and current API specs while I'm at it. Can't promise a ETA though.

**Comment by MeixDev** [comment]
Hi @Sharaddition 

Just wanted to point to you that this package is now deprecated, and should be replaced with my [discord_api](https://pub.dev/packages/discord_api) package instead. You'll need to handle your webviews/way of logging in on your own, but this package will help you for anything API-related.

As a side note, crypto isn't necessary anymore apparently, as the challenge doesn't seem to be necessary anymore, at least in my current tests (it also isn't part of the official documentation anymore).

Have a good day !
